2021-04-02 14:43:11 [11] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py lineno=578 funcname=run_with_reloader Watching for file changes with StatReloader
2021-04-02 14:43:13 [11] [WARNING] pathname=/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py lineno=114 funcname=decode Session data corrupted
2021-04-02 14:43:13 [11] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET / HTTP/1.1" 200 10419
2021-04-02 14:43:34 [11] [WARNING] pathname=/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py lineno=114 funcname=decode Session data corrupted
2021-04-02 14:43:34 [11] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /post/stage-certain-become-morning-jbrown-2021-04-02/ HTTP/1.1" 200 18904
2021-04-02 14:43:39 [11] [WARNING] pathname=/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py lineno=114 funcname=decode Session data corrupted
2021-04-02 14:43:39 [11] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET / HTTP/1.1" 200 10419
2021-04-02 14:44:40 [16] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py lineno=578 funcname=run_with_reloader Watching for file changes with StatReloader
2021-04-02 14:44:43 [16] [WARNING] pathname=/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py lineno=114 funcname=decode Session data corrupted
2021-04-02 14:44:43 [16] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET / HTTP/1.1" 200 10518
2021-04-02 15:17:50 [13] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py lineno=578 funcname=run_with_reloader Watching for file changes with StatReloader
2021-04-02 15:43:31 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py lineno=578 funcname=run_with_reloader Watching for file changes with StatReloader
2021-04-02 15:43:33 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET / HTTP/1.1" 200 10454
2021-04-02 15:44:52 [13] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py lineno=578 funcname=run_with_reloader Watching for file changes with StatReloader
2021-04-02 17:40:03 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py lineno=578 funcname=run_with_reloader Watching for file changes with StatReloader
2021-04-02 17:40:27 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET / HTTP/1.1" 200 10258
2021-04-02 17:40:27 [14] [WARNING] pathname=/usr/local/lib/python3.9/site-packages/django/utils/log.py lineno=222 funcname=log_response Not Found: /favicon.ico
2021-04-02 17:40:27 [14] [WARNING] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /favicon.ico HTTP/1.1" 404 3935
2021-04-02 17:40:29 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /admin/ HTTP/1.1" 302 0
2021-04-02 17:40:29 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1819
2021-04-02 17:40:29 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/css/login.css HTTP/1.1" 200 1233
2021-04-02 17:40:29 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/css/base.css HTTP/1.1" 200 16378
2021-04-02 17:40:29 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
2021-04-02 17:40:29 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
2021-04-02 17:40:30 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
2021-04-02 17:40:30 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
2021-04-02 17:40:32 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2021-04-02 17:40:32 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /admin/ HTTP/1.1" 200 8996
2021-04-02 17:40:32 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/css/base.css HTTP/1.1" 304 0
2021-04-02 17:40:32 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
2021-04-02 17:40:32 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
2021-04-02 17:40:32 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
2021-04-02 17:40:32 [14] [WARNING] pathname=/usr/local/lib/python3.9/site-packages/django/utils/log.py lineno=222 funcname=log_response Not Found: /img/icon-changelink.svg
2021-04-02 17:40:32 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
2021-04-02 17:40:32 [14] [WARNING] pathname=/usr/local/lib/python3.9/site-packages/django/utils/log.py lineno=222 funcname=log_response Not Found: /img/icon-addlink.svg
2021-04-02 17:40:32 [14] [WARNING] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /img/icon-changelink.svg HTTP/1.1" 404 3971
2021-04-02 17:40:32 [14] [WARNING] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /img/icon-addlink.svg HTTP/1.1" 404 3962
2021-04-02 17:40:32 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
2021-04-02 17:40:32 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/core/servers/basehttp.py lineno=154 funcname=log_message "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
2021-04-02 17:41:40 [14] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py lineno=203 funcname=trigger_reload /code/blog/settings.py changed, reloading.
2021-04-02 17:41:41 [24] [INFO] pathname=/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py lineno=578 funcname=run_with_reloader Watching for file changes with StatReloader
